### ISSUE TITLE
Script not found!

### ISSUE THREAD

**Issue by cristianrubioa** [YuePanEdward/MULLS#11]
script/run_mulls_slam.sh: 87: script/run_mulls_slam.sh: ./bin/mulls_slam: not found

**Comment by YuePanEdward** [comment]
Hi, please make sure the compiling is successfully done.
```
# cd to the base folder of MULLS
mkdir build
cd build
cmake ..
make 
cd ..
```

**Comment by xuwuzhou** [comment]
I meet the same problem, and i am sure that the compiling is successfully done

**Comment by xuwuzhou** [comment]
@YuePanEdward
