### ISSUE TITLE
diff between code and paper

### ISSUE THREAD

**Issue by FishInWave** [YuePanEdward/MULLS#12]
Hi, thanks for you outstanding work. I learned a lot from your paper and your code.
Howerver, there are some diffs between your paper and the code:
1. weight for xyz balance, according to your paper, w_ground should be "max_(0.01, z_xy_balance_ratio * (m2 + 2 * m3 + m4) / (0.0001 + 2.0 * m1))"
https://github.com/YuePanEdward/MULLS/blob/c0f79a21d55d2b5f86e6c00fd8fb696dce17e6c7/include/common/cregistration.hpp#L2013
2. wrong comment?
https://github.com/YuePanEdward/MULLS/blob/c0f79a21d55d2b5f86e6c00fd8fb696dce17e6c7/include/common/cregistration.hpp#L1229
```
		if (used_feature_type[1] == '1')
			source_feature_points_count += pc_pillar_sc->points.size();
		if (used_feature_type[2] == '1')
			source_feature_points_count += pc_facade_sc->points.size();
		if (used_feature_type[3] == '1')
			source_feature_points_count += pc_beam_sc->points.size();
```
It seems that the order of beam and facade in commet is wrong.

**Comment by YuePanEdward** [comment]
Thank you a lot. 
You are right. It's my blunder for both cases. I will correct them.

**Comment by HaisenbergPeng** [comment]
Hi, Mr. Pan, I too found some inconsistencies between the paper and the code. In equation (8), a negative sign is missed in Apo2po, and Apo2li seems to be wrong as well.
