### ISSUE TITLE
feature seg

### ISSUE THREAD

**Issue by ycloverrr** [YuePanEdward/MULLS#13]
how can i only show the lidar points feature segmentation

**Comment by YuePanEdward** [comment]
When the visualization is on, you can press F10 to turn on/off the visualization of lidar feature points in the feature window. For more instructions, please refer to [here](https://github.com/YuePanEdward/MULLS/wiki/GUI-instruction).

Example: 
![feature_viewer](https://user-images.githubusercontent.com/34207278/115040339-9f209c00-9ed1-11eb-8676-ce76fe368996.png)
