### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by christophTUM** [YuePanEdward/MULLS#16]
Hello,

if i try to run the algorithm with my own data i get the following output and everything shuts down:

`I0512 11:56:04.058781 18420 mulls_slam.cpp:205] Launch the program!`
`I0512 11:56:04.058979 18420 mulls_slam.cpp:206] Logging is written to ./log/test`
`W0512 11:56:04.367514 18420 mulls_slam.cpp:332] [8] threads availiable in total`
`Segmentation fault (core dumped)`

Does someone know a solution?

**Comment by YuePanEdward** [comment]
HI, is the issue solved? If not, would you mind providing us with some example data for this issue?

**Comment by christophTUM** [comment]
Yes the issue is solved, thanks! I had some erros in the script file. I got another issue regarding RAM i think. I will post it later.
