### ISSUE TITLE
Process killed

### ISSUE THREAD

**Issue by christophTUM** [YuePanEdward/MULLS#17]
Hi,

if i try to use apparently too much PCD Files the algorithm abruptly stopps displaying the message `killed` in the terminal, in the process of saving the map i think. (When it iterates through the pcd files at the end).
I guess it has to do with too little RAM?

I am using a MacBook Pro 2018.

**Comment by YuePanEdward** [comment]
Hi, thanks for your interest. 
I think you are correct. You may try to increase the parameter: `map_downrate_output` in the config file.
```
DEFINE_int32(map_downrate_output, 5, "downsampling rate for output map point cloud");
```

**Comment by christophTUM** [comment]
Does it change the resulting quality of the map? I havent read into the config much yet.

**Comment by YuePanEdward** [comment]
It depends on the used LiDAR and the required point density. For LiDARs such as HDL64, I think changing the downsample ratio to 10 would still result in a relatively dense map.
