### ISSUE TITLE
Parameter Modification

### ISSUE THREAD

**Issue by yufeilongyuan** [YuePanEdward/MULLS#19]
Hi, Author：
                           I have encountered some difficulties and hope to get your help. I recorded some point cloud data with 32 line radar. I want to see the road information clearly, such as the lane line. But when I finish our program, I can only see the outline of the road clearly, but I can't see the lane line clearly. How can I modify the configuration file parameters, please? Thank you.

**Comment by YuePanEdward** [comment]
Sorry for the late reply and thanks for your interest.
You may import the constructed map stored in the `result` folder into 3D Viewers such as CloudCompare and then configure the color map for intensity visualization.

**Comment by yufeilongyuan** [comment]
OK，Thanks.
