### ISSUE TITLE
how to save the final map?

### ISSUE THREAD

**Issue by su-zhao** [YuePanEdward/MULLS#30]
when mapping process is already done,I use Ctrl+C to end of the process,but map_point_clouds is empty.

**Comment by YuePanEdward** [comment]
Sorry for the late reply.  You can set `write_out_map_on=true` in the config file or the run_xxx.sh file. Then after the sequence is finished, all the raw point clouds would be loaded again, undistorted, merged and output to the map_point_clouds folder. You can also set the downsampling rate through the parameter `map_downrate_output`.
