### ISSUE TITLE
卡顿

### ISSUE THREAD

**Issue by xuwuzhou** [YuePanEdward/MULLS#32]
测试KITTI00，跑是可以正常跑，但是为什么非常卡顿，我的机器配置是ubuntu18+32G+i710700，我看了电脑资源利用率，内存只用了10G，cpu只用了10%，按理说不应该让机器卡顿，这是为什么呢

**Comment by YuePanEdward** [comment]
I think it might be the same problem as https://github.com/YuePanEdward/MULLS/issues/33#issuecomment-1048605502.
