### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by xuwuzhou** [YuePanEdward/MULLS#33]
I have some questions about MULLS that are bothering me, can you answer them?
1. **TIME consumption**  Although the terminal output of MULLS shows that the average time per frame is about 15ms, but in actual operation, I found that when the data is larger, the running speed of MULLS is slower. For example, when testing KITTI04, about It takes 10s (the average time consumption per frame is about 40ms), when testing KITTI02, it took about 2h (that is to say, the average time consumption per frame is about 1.5s, my computer configuration It's 32GB RAM, i710700, 1TSSD+2T mechanical hard drive, I don't think it's because of the computer configuration)，why caused this？ and is there any improvement plan?
2. **The relationship between the experimental data of the paper and the code parameters**  I noticed that you set three sets of parameters for the KITTI data set, so in the experimental data in the paper, do you use one set of parameters or all three sets of parameters?

**Comment by YuePanEdward** [comment]
Sorry for the late reply and thanks for your interest in this project. I am busy with other projects these days.
For the first question, I think it's the problem of pcl VTK's visualization latency. If you disable the visualization of frame-wise and submap features (by pressing 'F10') or directly set the `real_time_viewer_on=false` in the config file,  the operation would be much smoother. 
For the second question, I actually use two sets of parameters on KITTI (highway for seq01, seq.20, seq.21 and urban for all the others). The results of the open-source version of MULLS should be somehow consistent with the experiment results recorded in this paper [CT-ICP](https://arxiv.org/pdf/2109.12979.pdf).

**Comment by xuwuzhou** [comment]
Thanks for your sincerely reply
