### ISSUE TITLE
About the error of the ROS Vertion

### ISSUE THREAD

**Issue by xuwuzhou** [YuePanEdward/MULLS#34]
Thanks for your great open-source work

 Recently，I transplanted MULLS to a version of ROS, I think there's probably nothing wrong with my transplant, 
But a strange thing happened, the accuracy of  ROS version of MULLS is worse than the origin version. What do you think are the possible reasons? 

Ps: For some reasons, I can't open source code at present (I will open source it for a few months).

All of those results are without Loop closure.

Result is about KITTI00

The Ros Version: 

   max	29.731126
      mean	13.463498
    median	14.155483
       min	0.000000
      rmse	15.795527
       sse	1132973.519208
       std	8.260320

![2022-02-17 15-41-08 的屏幕截图](https://user-images.githubusercontent.com/44218507/154428492-a73bc364-df29-4509-a7a9-9e7796c91d9c.png)
![2022-02-17 15-41-20 的屏幕截图](https://user-images.githubusercontent.com/44218507/154428422-60fe03be-6bdb-4431-8b82-7c4d0ab3b211.png)

The origin version:
       max	23.285513
      mean	9.309443
    median	6.983857
       min	0.000000
      rmse	10.916848
       sse	541185.327411
       std	5.701915

![2022-02-17 15-44-15 的屏幕截图](https://user-images.githubusercontent.com/44218507/154428907-dea3f424-d76d-4a9c-b482-e86f2066b62c.png)
![2022-02-17 15-44-26 的屏幕截图](https://user-images.githubusercontent.com/44218507/154428917-14e16f0e-666f-4922-b43c-c96f850bfb60.png)

**Comment by xuwuzhou** [comment]
Fine, I got it. My parameters are wrong.

**Comment by YuePanEdward** [comment]
Thank you very much for your great contribution. I am busy with other projects so my ROS version is not ready to be open source.    It's great that you also did the code transplanting.

**Comment by kefa27** [comment]
Hello @xuwuzhou, 
I'm currently working on ROS support for MULLS and some other extensions as well and very curios about your work. 
Is it possible to get in contact with you? Unfortunately, I couldn't find any contact info on your profile.

Thanks in advance.

**Comment by xuwuzhou** [comment]
@kefa27 If you encounter a problem with ROS transplantation, I'd be happy to discuss it with you. My email is jackzhouweichao@163.com, but I've been busy looking for a job recently, and my reply may be slow
