### ISSUE TITLE
Run time 

### ISSUE THREAD

**Issue by xuwuzhou** [YuePanEdward/MULLS#35]
It seems that the runtime of  the open-sourced MULLS is much higher than the paper. In paper, it said that MULLS needs 80ms(without loop) or 100ms(with loop). But in my experiment, I find that the MULLS needs 154ms(without loop), about 1s(with loop), There is no changes between the code I run with your open-soured.

What causes this situation?

**Comment by xuwuzhou** [comment]
The average run time of MULLS in KITTI01 is even more than 400ms per frame, that is far away from the data in the paper, sir
 
Maybe I need a explanation

**Comment by YuePanEdward** [comment]
Sorry for the late reply and thanks for your interest in this project.  I am busy with other projects these days.
There could be two reasons.
The first is the visualization latency of VTK.  If you disable the visualization of frame-wise and submap features (by pressing 'F10'),  the operation would be much smoother. I wonder if you would notice the same phenomenon in your ROS implementation. 
The second is the hardware. If you run the code on a single-core CPU onboard a robot, such timing could be reasonable.

**Comment by xuwuzhou** [comment]
Let me have a try, thanks for your reply
