### ISSUE TITLE
How to remove dynamic objects

### ISSUE THREAD

**Issue by vikishaw2** [YuePanEdward/MULLS#36]
I tried parameters in congfig/demo.txt and kitti_urban.txt with sequence00/01 of KITTI  dataset, however, dynamic points are still in the file of "merged_map.pcd". Parameter of "apply_map_based_dynamic_removal" was also set to "true". How could I get merged points without dynamic objects? Thanks.

**Comment by YuePanEdward** [comment]
Thanks for your interest. MULLS actually only apply map based dynamic removal to the extracted feature points to get rid of the dynamic feature points for better scan alignment. The merged map for output is still accumulated from the raw point cloud and no dynamic objects are removed there. A MOS network like (https://github.com/PRBonn/LiDAR-MOS) and a static mapping framework like (https://github.com/irapkaist/removert) may meet your need.
