### ISSUE TITLE
Could you please provide some suggestions on how to adjust parameters on KITTI dataset? 

### ISSUE THREAD

**Issue by edward456** [YuePanEdward/MULLS#4]
Hi, yue pan, 

Thank you very much for sharing your code! Your work is awesome, which gives me a lot of inspiration. However, when I try to test KITTI00 data and run your code with your configuration (lo_gflag_list_kitti_urban.txt). I cannot obtain same results as you presented. Meanwhile, It seems that I cannot achieve real-time performance when testing your code. I think there must be something wrong with my configuration. However, I didn't change anything. Do you know the potential reasons?  Thank you very much for your help! 

**Here is the odometry result** 

![kitti00_odometry](https://user-images.githubusercontent.com/18071420/103258938-384c9680-4965-11eb-816b-0fac40e2dc21.png)

**Here is the SLAM result with loop closure** 

![kitti00_odometry_loop](https://user-images.githubusercontent.com/18071420/103258944-3da9e100-4965-11eb-8958-e881d47a38a4.png)

Thank you very much!

**Comment by YuePanEdward** [comment]
Thanks a lot for your feedback. 
I wonder if your KITTI 00 data is the [un-distorted data](http://www.cvlibs.net/download.php?file=data_odometry_velodyne.zip) or the [raw data](http://www.cvlibs.net/datasets/kitti/raw_data.php). If the motion compensation has not been done yet, the LiDAR odometry may have some problem. 

Here's my result using the KITTI 00 [un-distorted data](http://www.cvlibs.net/download.php?file=data_odometry_velodyne.zip) with the configuration file provided in this repository (lo_gflag_list_kitti_urban.txt):

**Here is the odometry result**
![lidar_odom_kitti_00](https://user-images.githubusercontent.com/34207278/103315595-4e6e5b80-4a26-11eb-8195-ad2a527d6a9e.png)


**Here is the SLAM result with loop closure**
![mulls_slam_kitti_00](https://user-images.githubusercontent.com/34207278/103314469-7c05d580-4a23-11eb-9c74-b5bc31c409f2.png)

**Comment by edward456** [comment]
Thanks for your quick reply! Yes, you are right! The results are pretty good. Congratulations!

**Comment by kefa27** [comment]
This post is quite helpful. I would like to ask which of the motion_compensation_method was chosen to get these results? (0: disabled, 1: uniform motion model, 2: from azimuth, 3: imu-assisted)
Thanks!
