### ISSUE TITLE
roof feature points number always 0

### ISSUE THREAD

**Issue by PyNancy** [YuePanEdward/MULLS#40]
Hi，nice project， i test on unground parking lot，but the roof feature points number always is 0；i use Velodyne_VLS128 and
 Hesai pandar64, but both are 0, do you have any idea or suggestions? thank you.

**Comment by YuePanEdward** [comment]
Sorry for the late reply. It's probably due to the parameter "roof_normal_ang". It should be set to a value smaller than 90 to enable the roof feature points.
