### ISSUE TITLE
IO time seems dominate the run time

### ISSUE THREAD

**Issue by linwk20** [YuePanEdward/MULLS#42]
Hi, Thanks for your sharing of this great work!
When I run MULLS on my dataset, the pcd IO seems contribute msot of the run time (95%+), as shown below, and the cpu utilization is very low:

I0824 16:12:37.009825  9307 mulls_slam.cpp:811] Consuming time of lidar odometry for current frame is [10.0236] ms.
I0824 16:12:37.009831  9307 mulls_slam.cpp:812] Process frame (including data IO) [210] in [669.144] ms.
I0824 16:12:37.668747  9307 dataio.hpp:157] A pcd file has been imported.

I wonder how can fix it?

Thanks!

**Comment by YuePanEdward** [comment]
Thanks for your interest on this project. You might try the following options:
1. Turn off the real-time visualization. Change the visualization flag to 0 in the script.
2. Make sure that the point cloud files are stored in somewhere like a ssd instead of a mechanical disk.
