### ISSUE TITLE
Question about the map drawing

### ISSUE THREAD

**Issue by Gatsby23** [YuePanEdward/MULLS#6]
Hi, I'm sorry, but could you please tell me, how to draw the point cloud like this ?
![image](https://user-images.githubusercontent.com/18000675/104113512-69e63a00-5335-11eb-95c8-533b691919df.png)
or this？
![Uploading image.png…]()
It looks really beautiful, so I want to test it on my project, could you give me some advice about that ? Thank you very much!

**Comment by YuePanEdward** [comment]
Thanks for your interest.
You may refer to the function 'display_lo_realtime' [here](https://github.com/YuePanEdward/MULLS/blob/main/include/common/map_viewer.hpp).

There are two options to draw the map point cloud. 
One is to use the realtime visualizer provided by this repository. You may configure the visualizer according to [here](https://github.com/YuePanEdward/MULLS/wiki/GUI-instruction).
The other is to show the output map point cloud in other softwares such as CloudCompare. You may configure the output settings according to [here](https://github.com/YuePanEdward/MULLS/wiki/MULLS-Visualization-Parameter-List).

**Comment by Gatsby23** [comment]
> Thanks for your interest.
> You may refer to the function 'display_lo_realtime' [here](https://github.com/YuePanEdward/MULLS/blob/main/include/common/map_viewer.hpp).
> 
> There are two options to draw the map point cloud.
> One is to use the realtime visualizer provided by this repository. You may configure the visualizer according to [here](https://github.com/YuePanEdward/MULLS/wiki/GUI-instruction).
> The other is to show the output map point cloud in other softwares such as CloudCompare. You may configure the output settings according to [here](https://github.com/YuePanEdward/MULLS/wiki/MULLS-Visualization-Parameter-List).

Thank you for your replay!
