### ISSUE TITLE
core dumped / too few necessary correspondences

### ISSUE THREAD

**Issue by WennPaper** [YuePanEdward/MULLS#9]
Hi, I'm trying to test MULLS with some LiDAR data that I collected in my apartment, however I just wasn't able to get it working properly. I have tried all the configuration files that are in the script/config folder, and depending on the config file I would get different messages. Below are the detailed descriptions of my problem.
1. Before getting into my problem, when I tried the example data in demo_data folder, except for Map Viewer, the rest three Viewers were always empty. Most GUI buttons (e.g. F1 - F12) were not working at all. I used Ubuntu 18.04.3 LTS in a virtual machine.
2. When I used lo_gflag_list_16.txt for my data (which is supposed to be the most suitable for my data since my LiDAR is Velodyne VLP-16), I got the following message:
...
I0312 13:14:30.965481 16036 dataio.hpp:910] Record the file: [./test1/pcd/760.pcd].
I0312 13:14:30.965485 16036 dataio.hpp:910] Record the file: [./test1/pcd/761.pcd].
**W0312 13:14:30.965608 16036 mulls_slam.cpp:332] [6] threads availiable in total**
The file has already existed, are you sure to overwrite it?  0. No  1. Yes [default 1]
1
I0312 13:14:37.337500 16036 dataio.hpp:1213] A new file [./test1/result/Rt_lo_xxx_id.txt] would be generated and used later
I0312 13:14:37.380396 16036 dataio.hpp:157] A pcd file has been imported.
I0312 13:14:37.380431 16036 dataio.hpp:212] [14528] points loaded in [42.6244] ms
I0312 13:14:37.380708 16036 cfilter.hpp:91] too small voxel size, the downsampling would be disabled
I0312 13:14:37.381307 16036 cfilter.hpp:1985] Ground: [0 | 0] Unground: [584].
I0312 13:14:37.381335 16036 cfilter.hpp:1991] Ground segmentation and normal estimation in [0.546499] ms. preparation in [0.1245] ms.
I0312 13:14:37.382174 16036 cfilter.hpp:2288] Unground geometric feature points extracted done in [0.810499] ms.
I0312 13:14:37.382205 16036 cfilter.hpp:2289] Details: pca in [0.781499] ms, geometric feature points extracted in [0.0149] ms, encoding keypoints in [0.0138] ms, nms sharpen in [0] ms, downsampling in [0.0003] ms.
I0312 13:14:37.382216 16036 cfilter.hpp:2290] Pillar: [1 | 0] Beam: [27 | 8] Facade: [113 | 54] Roof: [0 | 0] Vertex: [76].
I0312 13:14:37.419108 16036 dataio.hpp:157] A pcd file has been imported.
I0312 13:14:37.419142 16036 dataio.hpp:212] [14528] points loaded in [36.9146] ms
I0312 13:14:37.419378 16036 cfilter.hpp:91] too small voxel size, the downsampling would be disabled
I0312 13:14:37.419759 16036 cfilter.hpp:1985] Ground: [0 | 0] Unground: [572].
I0312 13:14:37.419788 16036 cfilter.hpp:1991] Ground segmentation and normal estimation in [0.328699] ms. preparation in [0.1164] ms.
I0312 13:14:37.420783 16036 cfilter.hpp:2288] Unground geometric feature points extracted done in [0.936699] ms.
I0312 13:14:37.420815 16036 cfilter.hpp:2289] Details: pca in [0.901299] ms, geometric feature points extracted in [0.0178] ms, encoding keypoints in [0.0174] ms, nms sharpen in [0.0001] ms, downsampling in [0.0001] ms.
I0312 13:14:37.420831 16036 cfilter.hpp:2290] Pillar: [1 | 0] Beam: [27 | 9] Facade: [121 | 47] Roof: [0 | 0] Vertex: [75].
I0312 13:14:37.420855 16036 map_manager.cpp:36] Map based filtering range(m): (0, 0.03] U [0.3,3]
I0312 13:14:37.420903 16036 map_manager.cpp:133] Feature point number of the local map: G: [0] P: [0] B: [8] F: [54] R: [0] V: [76].
I0312 13:14:37.420933 16036 map_manager.cpp:138] Update local map ([62] points at present) done in [0.0505] ms.
I0312 13:14:37.420995 16036 cregistration.hpp:1350] Build Kdtree done in [0.0275] ms
I0312 13:14:37.421021 16036 cregistration.hpp:1359] Apply initial guess transformation
1	0	0	0.5
0	1	0	0
0	0	1	0
0	0	0	1
I0312 13:14:37.421066 16036 cregistration.hpp:1379] Source point cloud updating done in [0.0446] ms for iteration [0]
mulls_slam: /build/pcl-OilVEB/pcl-1.8.1+dfsg1/kdtree/include/pcl/kdtree/impl/kdtree_flann.hpp:136: int pcl::KdTreeFLANN<PointT, Dist>::nearestKSearch(const PointT&, int, std::vector<int>&, std::vector<float>&) const [with PointT = pcl::PointXYZINormal; Dist = flann::L2_Simple<float>]: Assertion `point_representation_->isValid (point) && "Invalid (NaN, Inf) point coordinates given to nearestKSearch!"' failed.
Aborted (core dumped)
3. For all the rest configuration files, they all gave similar if not identical messages, and I needed to keep pressing space to go to the next frame of my data. It looked like the algorithm had a hard time extracting enough features. Note lo_gflag_list_example_demo.txt was the only file that made the Map Viewer display one frame of my data, and Map Viewer would be empty if I used other configuration files, which made no sense to me. Regardless the rest three Viewers were always empty. Here are the messages:
...
I0312 14:22:00.955034 17215 dataio.hpp:910] Record the file: [./test1/pcd/760.pcd].
I0312 14:22:00.955039 17215 dataio.hpp:910] Record the file: [./test1/pcd/761.pcd].
**W0312 14:22:00.955149 17215 mulls_slam.cpp:332] [6] threads availiable in total**
The file has already existed, are you sure to overwrite it?  0. No  1. Yes [default 1]
1
I0312 14:22:03.892556 17215 dataio.hpp:1213] A new file [./test1/result/Rt_lo_xxx_id.txt] would be generated and used later
I0312 14:22:03.940910 17215 dataio.hpp:157] A pcd file has been imported.
I0312 14:22:03.940933 17215 dataio.hpp:212] [14528] points loaded in [48.0784] ms
I0312 14:22:03.940984 17215 cfilter.hpp:91] too small voxel size, the downsampling would be disabled
I0312 14:22:03.942530 17215 cfilter.hpp:1985] Ground: [0 | 0] Unground: [13].
I0312 14:22:03.942560 17215 cfilter.hpp:1998] Ground segmentation done in [1.4904] ms.
I0312 14:22:03.942569 17215 cfilter.hpp:1999] Ground Normal Estimation done in [0.0008] ms. preparation in [0.2037] ms.
I0312 14:22:03.942642 17215 cfilter.hpp:2288] Unground geometric feature points extracted done in [0.0638] ms.
I0312 14:22:03.942685 17215 cfilter.hpp:2289] Details: pca in [0.0603] ms, geometric feature points extracted in [0.0008] ms, encoding keypoints in [0.0001] ms, nms sharpen in [0.0023] ms, downsampling in [0.0003] ms.
I0312 14:22:03.942696 17215 cfilter.hpp:2290] Pillar: [0 | 0] Beam: [1 | 0] Facade: [0 | 0] Roof: [0 | 0] Vertex: [0].
I0312 14:22:03.981065 17215 dataio.hpp:157] A pcd file has been imported.
I0312 14:22:03.981096 17215 dataio.hpp:212] [14528] points loaded in [38.3904] ms
I0312 14:22:03.981142 17215 cfilter.hpp:91] too small voxel size, the downsampling would be disabled
I0312 14:22:03.981544 17215 cfilter.hpp:1985] Ground: [0 | 0] Unground: [12].
I0312 14:22:03.981571 17215 cfilter.hpp:1998] Ground segmentation done in [0.3398] ms.
I0312 14:22:03.981608 17215 cfilter.hpp:1999] Ground Normal Estimation done in [0.0009] ms. preparation in [0.2246] ms.
I0312 14:22:03.981671 17215 cfilter.hpp:2288] Unground geometric feature points extracted done in [0.0467] ms.
I0312 14:22:03.981700 17215 cfilter.hpp:2289] Details: pca in [0.0429] ms, geometric feature points extracted in [0.0007] ms, encoding keypoints in [0.0005] ms, nms sharpen in [0.0022] ms, downsampling in [0.0004] ms.
I0312 14:22:03.981714 17215 cfilter.hpp:2290] Pillar: [0 | 0] Beam: [1 | 0] Facade: [0 | 0] Roof: [0 | 0] Vertex: [0].
I0312 14:22:03.981729 17215 map_manager.cpp:36] Map based filtering range(m): (0, 0.03] U [0.3,3]
I0312 14:22:03.981745 17215 map_manager.cpp:133] Feature point number of the local map: G: [0] P: [0] B: [0] F: [0] R: [0] V: [0].
I0312 14:22:03.981750 17215 map_manager.cpp:138] Update local map ([0] points at present) done in [0.0175] ms.
I0312 14:22:03.981770 17215 cregistration.hpp:3050] Intersection local bounding box filtering done
I0312 14:22:03.981778 17215 cregistration.hpp:1350] Build Kdtree done in [0.0014] ms
I0312 14:22:03.981784 17215 cregistration.hpp:1359] Apply initial guess transformation
1	0	0	0.5
0	1	0	0
0	0	1	0
0	0	0	1
I0312 14:22:03.981797 17215 cregistration.hpp:1379] Source point cloud updating done in [0.0138] ms for iteration [0]
I0312 14:22:03.981804 17215 cregistration.hpp:1412] Used correspondences [G: 0 P: 0 B: 0 F: 0 R: 0 V: 0 ].
I0312 14:22:03.981809 17215 cregistration.hpp:1414] Correspondence searching done in [0.0062] ms for iteration [0]
**W0312 14:22:03.981814 17215 cregistration.hpp:1424] Too few neccessary correspondences**
I0312 14:22:03.981828 17215 cregistration.hpp:1548] The posterior overlapping ratio is [-nan]
I0312 14:22:03.981833 17215 cregistration.hpp:1553] Registration done in [0.0695] ms.
I0312 14:22:03.981838 17215 cregistration.hpp:1554] Final tran. matrix:
1	0	0	0.5
0	1	0	0
0	0	1	0
0	0	0	1
Press [space] to continue
[space] was pressed => resume
I0312 14:22:06.766881 17215 mulls_slam.cpp:679] scan to scan registration done
frame [0] - [1]:
1	0	0	0.5
0	1	0	0
0	0	1	0
0	0	0	1
I0312 14:22:06.771096 17215 mulls_slam.cpp:773] Render frame [1] in [4.1485] ms.
I0312 14:22:06.771374 17215 common_nav.cpp:51] current approximate velocity: 18 (km/h)
I0312 14:22:06.771409 17215 mulls_slam.cpp:827] Consuming time of lidar odometry for current frame is [2785.8] ms.
I0312 14:22:06.771418 17215 mulls_slam.cpp:828] Process frame [1] in [2824.5] ms.
I0312 14:22:06.810683 17215 dataio.hpp:157] A pcd file has been imported.
I0312 14:22:06.810708 17215 dataio.hpp:212] [14528] points loaded in [39.2815] ms
I0312 14:22:06.810760 17215 cfilter.hpp:91] too small voxel size, the downsampling would be disabled
I0312 14:22:06.813957 17215 cfilter.hpp:1985] Ground: [0 | 0] Unground: [13].
I0312 14:22:06.813987 17215 cfilter.hpp:1998] Ground segmentation done in [3.1415] ms.
I0312 14:22:06.813997 17215 cfilter.hpp:1999] Ground Normal Estimation done in [0.0012] ms. preparation in [0.2118] ms.
I0312 14:22:06.815634 17215 cfilter.hpp:2288] Unground geometric feature points extracted done in [1.6279] ms.
I0312 14:22:06.815663 17215 cfilter.hpp:2289] Details: pca in [1.5722] ms, geometric feature points extracted in [0.0014] ms, encoding keypoints in [0.0008] ms, nms sharpen in [0.053] ms, downsampling in [0.0005] ms.
I0312 14:22:06.815675 17215 cfilter.hpp:2290] Pillar: [0 | 0] Beam: [3 | 0] Facade: [0 | 0] Roof: [0 | 0] Vertex: [3].
I0312 14:22:06.815685 17215 map_manager.cpp:36] Map based filtering range(m): (0, 0.03] U [0.3,3]
I0312 14:22:06.815701 17215 map_manager.cpp:133] Feature point number of the local map: G: [0] P: [0] B: [0] F: [0] R: [0] V: [0].
I0312 14:22:06.815704 17215 map_manager.cpp:138] Update local map ([0] points at present) done in [0.0175] ms.
I0312 14:22:06.815719 17215 cregistration.hpp:3050] Intersection local bounding box filtering done
I0312 14:22:06.815727 17215 cregistration.hpp:1350] Build Kdtree done in [0.0019] ms
I0312 14:22:06.815733 17215 cregistration.hpp:1359] Apply initial guess transformation
1	0	0	0
0	1	0	0
0	0	1	0
0	0	0	1
I0312 14:22:06.815785 17215 cregistration.hpp:1379] Source point cloud updating done in [0.0513] ms for iteration [0]
I0312 14:22:06.815796 17215 cregistration.hpp:1412] Used correspondences [G: 0 P: 0 B: 0 F: 0 R: 0 V: 0 ].
I0312 14:22:06.815800 17215 cregistration.hpp:1414] Correspondence searching done in [0.0117] ms for iteration [0]
**W0312 14:22:06.815804 17215 cregistration.hpp:1424] Too few neccessary correspondences**
I0312 14:22:06.815819 17215 cregistration.hpp:1548] The posterior overlapping ratio is [-nan]
I0312 14:22:06.815822 17215 cregistration.hpp:1553] Registration done in [0.1081] ms.
I0312 14:22:06.815826 17215 cregistration.hpp:1554] Final tran. matrix:
1	0	0	0
0	1	0	0
0	0	1	0
0	0	0	1
Press [space] to continue

Thanks for any help in advance!

**Comment by WenTheProgrammer** [comment]
I thought I may as well just attach some of my data here.
[test_data.zip](https://github.com/YuePanEdward/MULLS/files/6133072/test_data.zip)

**Comment by Laney097** [comment]
I have the same problem.
And I don't know how to write the configuration file.
I have tried to configure some figures but I failed.....
